/*
 * Copyright 2019 michael.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.uos.inf.did.abbozza.plugineditor.gui;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.UIManager;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author michael
 */
public class ClosableTabPanel extends javax.swing.JPanel implements ChangeListener {

    private final JPanel panel;
    private final JTabbedPane tabbedPane;
    /**
     * Creates new form ClosableTabPanel
     */
    public ClosableTabPanel(JTabbedPane tabbedPane, JPanel panel, String title) {
        this.panel = panel;
        this.tabbedPane = tabbedPane;
        
        initComponents();

        titleLabel.setText(title);
        closeButton.addMouseListener(new MouseAdapter()
        {
            @Override
            public void mouseClicked(MouseEvent e)
            {
                tabbedPane.remove(panel);
            }
        });
        
        titleLabel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                tabbedPane.setSelectedComponent(panel);
            }
        });
        
        tabbedPane.addChangeListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(32767, 20));
        setMinimumSize(new java.awt.Dimension(86, 20));
        setOpaque(false);
        setPreferredSize(null);
        setRequestFocusEnabled(false);
        setLayout(new java.awt.BorderLayout());

        titleLabel.setText("XXX");
        titleLabel.setToolTipText("");
        titleLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 2));
        titleLabel.setInheritsPopupMenu(false);
        titleLabel.setMaximumSize(new java.awt.Dimension(32000, 15));
        titleLabel.setMinimumSize(new java.awt.Dimension(10, 15));
        titleLabel.setPreferredSize(null);
        add(titleLabel, java.awt.BorderLayout.WEST);

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/uos/inf/did/abbozza/plugineditor/close.png"))); // NOI18N
        closeButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        closeButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        closeButton.setMaximumSize(new java.awt.Dimension(16, 16));
        closeButton.setMinimumSize(new java.awt.Dimension(16, 16));
        closeButton.setPreferredSize(new java.awt.Dimension(16, 16));
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        add(closeButton, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_closeButtonActionPerformed


    public void setTitle(String title) {
        titleLabel.setText(title);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void stateChanged(ChangeEvent e) {
        if ( tabbedPane.getSelectedComponent() == panel ) {
            this.setBackground(UIManager.getColor("activeCaption")); 
        } else {
            this.setBackground(null);            
        }
    }

}
