/*
 * Copyright 2019 michael.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.uos.inf.did.abbozza.plugineditor.gui;

import de.uos.inf.did.abbozza.plugineditor.FileEntry;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author michael
 */
public class FileDialog extends javax.swing.JDialog {

    public int state;
    private PluginFrame frame;
    
    /**
     * Creates new form FileDialog
     * @param parent
     * @param modal
     * @param entry
     */
    public FileDialog(java.awt.Frame parent, boolean modal, FileEntry entry) {
        super(parent, modal);
        initComponents();
        frame = (PluginFrame) parent;
        
        if (entry != null) {
            nameField.setText(entry.getName());
            targetField.setText(entry.getTarget());
            switch (entry.getType()) {
                case FileEntry.TYPE_JS:
                    jsButton.setSelected(true);
                    break;
                case FileEntry.TYPE_JAVA:
                    jvButton.setSelected(true);
                    otherButton.setEnabled(true);
                    panelButton.setEnabled(true);
                    listenerButton.setEnabled(true);
                    httpButton.setEnabled(true);
                    switch ( entry.getJavaType() ) {
                        case FileEntry.JTYPE_PANEL : 
                            panelButton.setSelected(true);
                            prefixLabel.setEnabled(true);
                            prefixField.setEnabled(true);
                            prefixField.setEditable(true);
                            break;
                        case FileEntry.JTYPE_LISTENER : 
                            listenerButton.setSelected(true);
                            prefixLabel.setEnabled(true);
                            prefixField.setEnabled(true);
                            prefixField.setEditable(true);
                            break;
                        case FileEntry.JTYPE_HTTP : 
                            httpButton.setSelected(true);
                            break;
                        default  : 
                            otherButton.setSelected(true);
                            break;
                    }
                    break;
                case FileEntry.TYPE_INSTALL:
                    inButton.setSelected(true);
                    targetLabel.setEnabled(true);
                    targetField.setEnabled(true);
                    break;
                default:
                    jsButton.setSelected(true);
                    break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeGroup = new javax.swing.ButtonGroup();
        handlerGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jsButton = new javax.swing.JRadioButton();
        jvButton = new javax.swing.JRadioButton();
        inButton = new javax.swing.JRadioButton();
        miButton = new javax.swing.JRadioButton();
        targetLabel = new javax.swing.JLabel();
        targetField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        httpButton = new javax.swing.JRadioButton();
        panelButton = new javax.swing.JRadioButton();
        listenerButton = new javax.swing.JRadioButton();
        otherButton = new javax.swing.JRadioButton();
        prefixLabel = new javax.swing.JLabel();
        prefixField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Name");

        typeGroup.add(jsButton);
        jsButton.setSelected(true);
        jsButton.setText("Javascript File");
        jsButton.setToolTipText("");
        jsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsButtonActionPerformed(evt);
            }
        });

        typeGroup.add(jvButton);
        jvButton.setText("Java File");
        jvButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jvButtonItemStateChanged(evt);
            }
        });

        typeGroup.add(inButton);
        inButton.setText("File to be installed");
        inButton.setToolTipText("");
        inButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                inButtonStateChanged(evt);
            }
        });

        typeGroup.add(miButton);
        miButton.setText("Misc file");

        targetLabel.setText("Target");
        targetLabel.setEnabled(false);

        targetField.setEditable(false);
        targetField.setEnabled(false);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        handlerGroup.add(httpButton);
        httpButton.setText("Http handler");
        httpButton.setEnabled(false);

        handlerGroup.add(panelButton);
        panelButton.setText("Monitor panel");
        panelButton.setEnabled(false);
        panelButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                panelButtonItemStateChanged(evt);
            }
        });

        handlerGroup.add(listenerButton);
        listenerButton.setText("Monito listener");
        listenerButton.setEnabled(false);
        listenerButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listenerButtonItemStateChanged(evt);
            }
        });
        listenerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listenerButtonActionPerformed(evt);
            }
        });

        handlerGroup.add(otherButton);
        otherButton.setSelected(true);
        otherButton.setText("Other");
        otherButton.setEnabled(false);

        prefixLabel.setText("Prefix");
        prefixLabel.setEnabled(false);

        prefixField.setEditable(false);
        prefixField.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(targetLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(targetField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inButton)
                            .addComponent(jvButton)
                            .addComponent(jsButton)
                            .addComponent(miButton))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(otherButton)
                            .addComponent(httpButton)
                            .addComponent(listenerButton)
                            .addComponent(panelButton))
                        .addGap(0, 103, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(prefixLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(prefixField)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(httpButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jvButton)
                    .addComponent(panelButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inButton)
                    .addComponent(listenerButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(miButton)
                    .addComponent(otherButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(targetLabel)
                    .addComponent(targetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prefixLabel)
                    .addComponent(prefixField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        state = 1;
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void inButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_inButtonStateChanged
        if (inButton.isSelected()) {
            targetField.setEnabled(true);
            targetLabel.setEnabled(true);
            targetField.setEditable(true);
        } else {
            targetField.setEnabled(false);
            targetLabel.setEnabled(false);
            targetField.setEditable(false);
        }
    }//GEN-LAST:event_inButtonStateChanged

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        state = 0;
        this.setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    private void listenerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listenerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listenerButtonActionPerformed

    private void jvButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jvButtonItemStateChanged
        if (jvButton.isSelected()) {
            httpButton.setEnabled(true);
            panelButton.setEnabled(true);
            listenerButton.setEnabled(true);
            otherButton.setEnabled(true);
        } else {
            httpButton.setEnabled(false);
            panelButton.setEnabled(false);
            listenerButton.setEnabled(false);
            otherButton.setEnabled(false);
        }
    }//GEN-LAST:event_jvButtonItemStateChanged

    private void panelButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_panelButtonItemStateChanged
        if (panelButton.isSelected()) {
            prefixField.setEnabled(true);
            prefixLabel.setEnabled(true);
            prefixField.setEditable(true);
        } else {
            prefixField.setEnabled(false);
            prefixLabel.setEnabled(false);
            prefixField.setEditable(false);
        }
    }//GEN-LAST:event_panelButtonItemStateChanged

    private void listenerButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listenerButtonItemStateChanged
        if (listenerButton.isSelected()) {
            prefixField.setEnabled(true);
            prefixLabel.setEnabled(true);
            prefixField.setEditable(true);
        } else {
            prefixField.setEnabled(false);
            prefixLabel.setEnabled(false);
            prefixField.setEditable(false);
        }
    }//GEN-LAST:event_listenerButtonItemStateChanged

    @Override
    public String getName() {
        return nameField.getText();
    }
    
    public String getTarget() {
        return targetField.getText();        
    }
    
    public String getPrefix() {
        return prefixField.getText();        
    }

    public int getFileType() {
        if ( jsButton.isSelected() ) return FileEntry.TYPE_JS;
        if ( jvButton.isSelected() ) return FileEntry.TYPE_JAVA;
        if ( inButton.isSelected() ) return FileEntry.TYPE_INSTALL;
        return FileEntry.TYPE_MISC;
    }
    
    public int getJavaType() {
        if ( otherButton.isSelected() ) return FileEntry.JTYPE_OTHER;
        if ( httpButton.isSelected() ) return FileEntry.JTYPE_HTTP;
        if ( panelButton.isSelected() ) return FileEntry.JTYPE_PANEL;
        return FileEntry.JTYPE_LISTENER;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.ButtonGroup handlerGroup;
    private javax.swing.JRadioButton httpButton;
    private javax.swing.JRadioButton inButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jsButton;
    private javax.swing.JRadioButton jvButton;
    private javax.swing.JRadioButton listenerButton;
    private javax.swing.JRadioButton miButton;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton okButton;
    private javax.swing.JRadioButton otherButton;
    private javax.swing.JRadioButton panelButton;
    private javax.swing.JTextField prefixField;
    private javax.swing.JLabel prefixLabel;
    private javax.swing.JTextField targetField;
    private javax.swing.JLabel targetLabel;
    private javax.swing.ButtonGroup typeGroup;
    // End of variables declaration//GEN-END:variables
}
