/*
 * Copyright 2019 michael.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.uos.inf.did.abbozza.plugineditor.gui;

import de.uos.inf.did.abbozza.plugineditor.FileEntry;
import de.uos.inf.did.abbozza.plugineditor.GUITool;
import de.uos.inf.did.abbozza.plugineditor.IllegalPluginException;
import de.uos.inf.did.abbozza.plugineditor.PluginEditor;
import de.uos.inf.did.abbozza.plugineditor.XMLTool;
import de.uos.inf.did.abbozza.plugineditor.systems.ArduinoManager;
import de.uos.inf.did.abbozza.plugineditor.systems.CalliopeManager;
import de.uos.inf.did.abbozza.plugineditor.systems.MonitorManager;
import de.uos.inf.did.abbozza.plugineditor.systems.SystemManager;
import de.uos.inf.did.abbozza.plugineditor.systems.WorldsManager;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.nio.file.FileVisitResult;
import java.nio.file.FileVisitor;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.Collection;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Set;
import java.util.jar.JarFile;
import java.util.jar.JarOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.zip.ZipEntry;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;

/**
 *
 * @author michael
 */
public class PluginFrame extends javax.swing.JFrame {

    // protected Plugin plugin;
    protected String pluginPath;

    protected PluginInfoPanel infoPanel;
    protected PluginFeaturePanel featurePanel;
    protected PluginOptionsPanel optionsPanel;
    protected PluginLanguagePanel languagePanel;
    protected PluginFilesPanel filesPanel;

    protected boolean changed;

    protected HashMap<String, SystemManager> systems;
    protected SystemManager systemManager;

    protected Image errorIcon;
    
    public Collection<SystemManager> getSystems() {
        return systems.values();
    }

    /**
     * Creates new PluginFrame.
     *
     * @param pluginPath The path for the plugin
     * @throws IllegalPluginException
     */
    public PluginFrame(String pluginPath) throws IllegalPluginException {
        // Register system managers
        systems = new LinkedHashMap();
        systems.put("arduino", new ArduinoManager(this));
        systems.put("calliopeC", new CalliopeManager(this));
        systems.put("worlds", new WorldsManager(this));
        systems.put("monitor", new MonitorManager(this));
        
        try {
            errorIcon = ImageIO.read(PluginEditor.class.getResourceAsStream("error.png"));
        } catch (IOException ex) {
            errorIcon = null;
        }

        // If the plugin path is null, ask for a plugin path
        if (pluginPath == null) {
            this.pluginPath = askForPlugin();

            // Exit, if no path is selected.
            if (this.pluginPath == null) {
                System.exit(1);
            }
        } else {
            this.pluginPath = pluginPath;
        }

        Document xml = openPluginPath();

        initComponents();

        changed = false;

        infoPanel = new PluginInfoPanel(this);
        infoContainer.add(infoPanel);

        featurePanel = new PluginFeaturePanel(this);
        fileContainer.add(featurePanel);

        optionsPanel = new PluginOptionsPanel(this);
        fileContainer.add(optionsPanel);

        languagePanel = new PluginLanguagePanel(this);
        fileContainer.add(languagePanel);

        filesPanel = new PluginFilesPanel(this);
        infoContainer.add(filesPanel);

        load(xml);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        footerPanel = new javax.swing.JPanel();
        changeLabel = new javax.swing.JLabel();
        statusMsg = new javax.swing.JTextField();
        pathField = new javax.swing.JTextField();
        statusIcon = new javax.swing.JLabel();
        infoContainer = new javax.swing.JTabbedPane();
        fileContainer = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        newMenuItem = new javax.swing.JMenuItem();
        renameItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        saveMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        closeMenuItem = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        settingsItem = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        quitMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        buildItem = new javax.swing.JMenuItem();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("abbozza! Plugin Editor");
        setMinimumSize(new java.awt.Dimension(440, 500));

        footerPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        changeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changeLabel.setText("*");

        statusMsg.setEditable(false);
        statusMsg.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        statusMsg.setBorder(null);

        pathField.setEditable(false);
        pathField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pathField.setText("<to be loaded>");
        pathField.setBorder(null);

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerPanelLayout.createSequentialGroup()
                .addComponent(changeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(statusMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(pathField, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(changeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(statusMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(pathField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(statusIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("File");

        openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMenuItem.setText("Open plugin");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(openMenuItem);

        newMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newMenuItem.setText("New plugin");
        newMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(newMenuItem);

        renameItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_MASK));
        renameItem.setText("Reload");
        renameItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renameItemActionPerformed(evt);
            }
        });
        jMenu1.add(renameItem);
        jMenu1.add(jSeparator2);

        saveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveMenuItem.setText("Save");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(saveMenuItem);
        jMenu1.add(jSeparator1);

        closeMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        closeMenuItem.setText("Close");
        closeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(closeMenuItem);
        jMenu1.add(jSeparator3);

        settingsItem.setText("Settings");
        settingsItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsItemActionPerformed(evt);
            }
        });
        jMenu1.add(settingsItem);
        jMenu1.add(jSeparator4);

        quitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        quitMenuItem.setText("Quit");
        quitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(quitMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Plugin");

        buildItem.setText("Build Jar");
        buildItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildItemActionPerformed(evt);
            }
        });
        jMenu2.add(buildItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(footerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(infoContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(fileContainer))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoContainer)
                    .addComponent(fileContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE))
                .addComponent(footerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMenuItemActionPerformed
        Document newXml;
        String oldPluginPath;
        String newPluginPath = askForPlugin();
        if (newPluginPath != null) {
            oldPluginPath = pluginPath;
            pluginPath = newPluginPath;
            try {
                newXml = openPluginPath();
                load(newXml);
            } catch (IllegalPluginException ex) {
                PluginEditor.showErrorMessage(ex.getMsg());
                pluginPath = oldPluginPath;
            }
        }
    }//GEN-LAST:event_newMenuItemActionPerformed

    private void quitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitMenuItemActionPerformed
        quit();
    }//GEN-LAST:event_quitMenuItemActionPerformed

    private void closeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeMenuItemActionPerformed
        quit();
    }//GEN-LAST:event_closeMenuItemActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        Document newXml;
        String oldPluginPath;
        String newPluginPath = askForPlugin();
        if (newPluginPath != null) {
            oldPluginPath = pluginPath;
            pluginPath = newPluginPath;
            try {
                newXml = openPluginPath();
                load(newXml);
            } catch (IllegalPluginException ex) {
                PluginEditor.showErrorMessage(ex.getMsg());
                pluginPath = oldPluginPath;
            }
        }
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        setStatusMsg("Saving ...");
        try {
            save();
            setStatusMsg("Saved successfully!");
            changed = false;
            this.uppateChanged();
        } catch (IOException ex) {
            setStatusMsg("Error during saving!");
        }
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void renameItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renameItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_renameItemActionPerformed

    private void settingsItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsItemActionPerformed
        PluginEditor.openConfigDialog();
    }//GEN-LAST:event_settingsItemActionPerformed

    private void buildItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildItemActionPerformed
        buildJar();
    }//GEN-LAST:event_buildItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem buildItem;
    private javax.swing.JLabel changeLabel;
    private javax.swing.JMenuItem closeMenuItem;
    protected javax.swing.JTabbedPane fileContainer;
    private javax.swing.JPanel footerPanel;
    protected javax.swing.JTabbedPane infoContainer;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenuItem newMenuItem;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JTextField pathField;
    private javax.swing.JMenuItem quitMenuItem;
    private javax.swing.JMenuItem renameItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JMenuItem settingsItem;
    private javax.swing.JLabel statusIcon;
    private javax.swing.JTextField statusMsg;
    // End of variables declaration//GEN-END:variables

    /**
     * Ask the user for a plugin path.
     *
     * @return The selected path. If the selection is aborted null is returned.
     */
    protected String askForPlugin() {
        String dir = null;

        JFileChooser chooser = new JFileChooser();
        FileFilter filter = new FileFilter() {
            @Override
            public boolean accept(File pathname) {
                return pathname.isDirectory();
            }

            @Override
            public String getDescription() {
                return "Plugin directory";
            }
        };
        chooser.setFileFilter(filter);
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setDialogTitle("Choose directory of plugin");
        chooser.setApproveButtonText("Choose directory");

        if (pluginPath != null) {
            chooser.setCurrentDirectory((new File(pluginPath)).getParentFile());
        }

        int returnVal = chooser.showOpenDialog(null);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File pluginDir = chooser.getSelectedFile();
            dir = pluginDir.getAbsolutePath();
        }

        return dir;
    }

    /**
     * Open the plugin path and return the describing plugin.xml.
     *
     * @return The Document representing plugin.xml.
     * @throws IllegalPluginException If the plugin is corrupted or can't be
     * created.
     */
    protected Document openPluginPath() throws IllegalPluginException {
        Document xml = null;
        File directory = new File(pluginPath);

        // If the directory doesn't exist ...
        if (!directory.exists()) {
            // ... create it
            try {
                Files.createDirectories(directory.toPath());
            } catch (IOException ex) {
                throw new IllegalPluginException("Can't create " + directory.getAbsolutePath());
            }
        }

        // Open the plugin.xml
        File xmlFile = new File(directory, "plugin.xml");
        if (!xmlFile.exists()) {
            // If it doesn't exist, create it from template
            askForSystem();
            writeTemplate("templates/plugin.tmpl", "plugin.xml");
        }

        try {
            xml = XMLTool.getXml(xmlFile.toURI().toURL());
        } catch (MalformedURLException ex) {
            throw new IllegalPluginException("File " + xmlFile.getAbsolutePath() + " is no vaild XML file");
        }

        PluginEditor.setLastPluginPath(pluginPath);

        return xml;
    }

    /**
     * Load the plugin from the given XML-Document.
     *
     * @param xml The document
     */
    protected void load(Document xml) throws IllegalPluginException {
        Element plugin = null;

        if (xml != null) {
            NodeList plugins = xml.getElementsByTagName("plugin");
            if (plugins.getLength() == 0) {
                throw new IllegalPluginException("No plugin tag defined in plugin.xml");
            }

            try {
                plugin = (Element) plugins.item(0);
            } catch (ClassCastException ex) {
                throw new IllegalPluginException("No plugin tag defined in plugin.xml");
            }

            String system = plugin.getAttribute("system");
            systemManager = systems.get(system);
            if (systemManager == null) {
                throw new IllegalPluginException("Unknown System " + system);
            }

            pathField.setText("[" + systemManager.getSystem() + "] " + pluginPath);

            // Reset the panels
            for (Component panelRaw : infoContainer.getComponents()) {
                try {
                    PluginPanel panel = (PluginPanel) panelRaw;
                    if (!panel.isBasePanel()) {
                        infoContainer.remove(panelRaw);
                    }
                } catch (ClassCastException ex) {
                }
            }

            for (Component panelRaw : fileContainer.getComponents()) {
                try {
                    PluginPanel panel = (PluginPanel) panelRaw;
                    if (!panel.isBasePanel()) {
                        fileContainer.remove(panelRaw);
                    }
                } catch (ClassCastException ex) {
                }
            }

            // Insert the system specific panel
            systemManager.initPanels();

            // Reset the panels
            for (Component panelRaw : infoContainer.getComponents()) {
                try {
                    PluginPanel panel = (PluginPanel) panelRaw;
                    panel.load(plugin);
                } catch (ClassCastException ex) {
                }
            }

            for (Component panelRaw : fileContainer.getComponents()) {
                try {
                    PluginPanel panel = (PluginPanel) panelRaw;
                    panel.load(plugin);
                } catch (ClassCastException ex) {
                }
            }

            infoContainer.setSelectedComponent(infoPanel);
        }
    }

    /**
     * Save the current plugin.
     *
     * @throws IOException
     */
    protected void save() throws IOException {
        File xmlFile = new File(pluginPath, "plugin.xml");
        if (!xmlFile.exists()) {
            Files.createFile(xmlFile.toPath());
        }

        try {
            DocumentBuilderFactory builderFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder builder = builderFactory.newDocumentBuilder();
            Document xml = builder.newDocument();
            Element root = (Element) xml.createElement("plugin");
            xml.appendChild(root);

            String system = systemManager.getSystem();
            root.setAttribute("system", system);

            for (Component panelRaw : infoContainer.getComponents()) {
                try {
                    PluginPanel panel = (PluginPanel) panelRaw;
                    panel.save(xml, root);
                } catch (ClassCastException ex) {
                }
            }

            for (Component panelRaw : fileContainer.getComponents()) {
                try {
                    PluginPanel panel = (PluginPanel) panelRaw;
                    panel.save(xml, root);
                } catch (ClassCastException ex) {
                }
            }

            String text = XMLTool.documentToString(xml);
            // System.out.println(text);
            File file = new File(pluginPath + "/plugin.xml");
            FileWriter writer = new FileWriter(file);
            writer.write(text);
            writer.close();
        } catch (ParserConfigurationException ex) {
        }

    }

    /**
     * Call build on all panels. Abort as soon as one returns an error.
     * @return 
     */
    public boolean build() {
        try {
            save();
        } catch (IOException ex) {
            setStatusMsg("Couldn't save the plugin");
            return false;
        }
        
        // Reset the panels
        for (Component panelRaw : infoContainer.getComponents()) {
            try {
                PluginPanel panel = (PluginPanel) panelRaw;
                if ( !panel.build() ) {
                    return false;
                }
            } catch (ClassCastException ex) {
            }
        }

        for (Component panelRaw : fileContainer.getComponents()) {
            try {
                PluginPanel panel = (PluginPanel) panelRaw;
                if ( !panel.build() ) {
                    return false;
                }
            } catch (ClassCastException ex) {
            }            
        }
        
        return true;
    }

    /**
     * Quit the program.
     */
    protected void quit() {
        if (changed) {
            int choice = JOptionPane.showConfirmDialog(this, "Save the plugin", "abbozza! Plugin Editor", JOptionPane.YES_NO_CANCEL_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                try {
                    save();
                } catch (IOException ex) {
                    this.setStatusMsg("Could not save plugin!");
                }
            } else if (choice == JOptionPane.NO_OPTION) {
                dispose();
            }
        } else {
            dispose();
        }
        HelpFrame.hideFrame();
    }

    /**
     * Display the given status nessage
     *
     * @param msg
     */
    public void setStatusMsg(String msg) {
        statusMsg.setText(msg);
        statusIcon.setIcon(null);
    }

    /**
     * Display the given status nessage
     *
     * @param msg
     */
    public void setErrorMsg(String msg) {
        statusMsg.setText(msg);
        statusIcon.setIcon(new ImageIcon(errorIcon));        
    }


    /**
     * Update the change indicator.
     */
    public void uppateChanged() {
        if (changed) {
            changeLabel.setText("*");
        } else {
            changeLabel.setText(" ");
        }
    }

    /**
     * Return the id of the current plugin.
     *
     * @return The id.
     */
    public String getId() {
        return infoPanel.getId();
    }

    /**
     * Returns the system of the plugin.
     *
     * @return
     */
    public String getSystem() {
        return systemManager.getSystem();
    }

    /**
     * Get the content of the given file as String.
     *
     * @param entry
     * @return
     */
    public String getFileContent(FileEntry entry) {
        StringBuffer content = new StringBuffer();
        int bufSize = 2048;
        int read;
        char[] buf = new char[bufSize];

        File file = new File(this.pluginPath + "/" + entry.getName());
        if (!file.exists()) {
            try {
                // The file doesn't exist, read the tempate
                InputStreamReader reader = new InputStreamReader(PluginEditor.class.getResourceAsStream("templates/javascript.tmpl"));
                while (reader.ready()) {
                    read = reader.read(buf, 0, bufSize);
                    content.append(buf, 0, read);
                }
            } catch (IOException ex) {
                Logger.getLogger(PluginFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                // Load the file
                FileReader reader = new FileReader(file);
                while (reader.ready()) {
                    read = reader.read(buf, 0, bufSize);
                    content.append(buf, 0, read);
                }
            } catch (MalformedURLException ex) {
                Logger.getLogger(PluginFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(PluginFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        return content.toString();
    }

    /**
     * Write the content to the given file.
     *
     * @param entry The FileEntry representing the file
     * @param content The content to be written
     */
    public void writeFileContent(FileEntry entry, String content) {
        int bufSize = 2048;
        int read;
        char[] buf = new char[bufSize];

        try {
            File file = new File(this.pluginPath + "/" + entry.getName());
            FileWriter writer = new FileWriter(file);
            writer.write(content);
            writer.close();
        } catch (IOException ex) {
            PluginEditor.showErrorMessage("Can't write to " + this.pluginPath + "/" + entry.getName());
        }
    }

    /**
     * Write a specific template to the given target.
     *
     * The following placeholders are replaced: %%SYSTEM%% by the current
     * system-
     *
     * @param template
     * @param target
     */
    public void writeTemplate(String template, String target) {
        if (template == null) {
            return;
        }

        StringBuffer buffer = new StringBuffer();
        int bufSize = 2048;
        int read;
        char[] buf = new char[bufSize];

        try {
            File targetFile = new File(this.pluginPath + "/" + target);

            // The file doesn't exist, read the tempate
            InputStreamReader reader = new InputStreamReader(PluginEditor.getResourceAsStream(template));
            while (reader.ready()) {
                read = reader.read(buf, 0, bufSize);
                buffer.append(buf, 0, read);
            }

            // Now replace the placeholders
            String content = buffer.toString();
            content = content.replace("%%SYSTEM%%", systemManager.getSystem());
            content = content.replace("%%CLASSNAME%%", target.replace(".java", ""));

            // Now write it to the target
            FileWriter writer = new FileWriter(targetFile);
            writer.write(content);
            writer.close();
        } catch (IOException ex) {
            Logger.getLogger(PluginFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * Ask the user for the system.
     */
    public void askForSystem() {
        SystemDialog dialog = new SystemDialog(this);
        GUITool.centerWindow(dialog);
        dialog.setVisible(true);

        if (dialog.getState() == 0) {
            systemManager = dialog.getSystem();
        } else {
            System.exit(1);
        }
    }

    public String getPluginPath() {
        return pluginPath;
    }

    public void addFileContainerPanel(JPanel panel, boolean closable) {
        fileContainer.add(panel);
        if (closable) {
            fileContainer.setTabComponentAt(fileContainer.indexOfComponent(panel), new ClosableTabPanel(fileContainer, panel, panel.getName()));
        }
        fileContainer.setSelectedComponent(panel);
    }

    public void addInfoContainerPanel(JPanel panel, boolean closable) {
        infoContainer.add(panel);
        if (closable) {
            infoContainer.setTabComponentAt(infoContainer.indexOfComponent(panel), new ClosableTabPanel(infoContainer, panel, panel.getName()));
        }
        infoContainer.setSelectedComponent(panel);
    }

    /**
     * Build a jar containig all files in the plugin directory.
     */
    public void buildJar() {
        if ( !build() ) return;

        File source = new File(pluginPath);
        File target;
        
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Jar File", "jar");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            target = chooser.getSelectedFile();
        } else {
            return;
        }
        
        try {
            JarOutputStream out = new JarOutputStream(new FileOutputStream(target));
            Files.walkFileTree( source.toPath(), new FileVisitor<Path>() {
                @Override
                public FileVisitResult preVisitDirectory(Path dir, BasicFileAttributes attrs) throws IOException {
                    return FileVisitResult.CONTINUE;
                }

                @Override
                public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) throws IOException {
                    String name = file.toRealPath().toString();
                    name = name.replace(pluginPath + "/","");
                    System.out.println(name);
                    out.putNextEntry(new ZipEntry(name));
                    Files.copy(file, out);
                    return FileVisitResult.CONTINUE;
                }

                @Override
                public FileVisitResult visitFileFailed(Path file, IOException exc) throws IOException {
                    return FileVisitResult.CONTINUE;
                }

                @Override
                public FileVisitResult postVisitDirectory(Path dir, IOException exc) throws IOException {
                    return FileVisitResult.CONTINUE;
                }
            });
            out.close();
        } catch (IOException ex) {
            Logger.getLogger(PluginFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
}
